name: ChadSyme
favicon: null
layout_spectrum: 0.12719007465057075
typography_spectrum: 0.18987621506676078
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.30296439304947853
  lightness: 0.47975508216768503
  saturation: 0.004460812779143453
  rhythmicContrast: 0.46585149341262877
purpose: []
