name: ChadSyme
favicon: null
layout_spectrum: 0
typography_spectrum: 0.40666
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffe3'
    - '#25294e'
    - '#abd7bc'
    - '#f1622c'
    - '#648488'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
